"use client";
import { useEffect, useMemo, useRef, useState } from "react";

const emptyCampaign = { theme: "", objective: "", instagramFormat: "carousel", separateTikTok: false, date: "" };
const iso = date => new Date(date).toISOString().slice(0, 10);
const plusDays = (date, days) => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + days); return iso(next); };
const platformOrder = { Instagram: 1, TikTok: 2, LinkedIn: 3 };

export default function ContentStudio({ member }) {
  const [calendar, setCalendar] = useState([]), [campaigns, setCampaigns] = useState([]), [form, setForm] = useState(emptyCampaign);
  const [tab, setTab] = useState("generator"), [sources, setSources] = useState([]), [mismatches, setMismatches] = useState([]), [notice, setNotice] = useState("Loading shared system…");
  const [analysis, setAnalysis] = useState(null), [active, setActive] = useState(null);
  const uploadRef = useRef(null);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("tab"); if (["generator","calendar","sources","review"].includes(requested)) setTab(requested); Promise.all([fetch("/api/workspace").then(r => r.json()), fetch("/api/sources").then(r => r.json())]).then(([workspace, docs]) => { setCalendar(workspace.state?.calendar || []); setCampaigns(workspace.state?.campaigns || []); setSources(docs.documents || []); setMismatches(docs.mismatches || []); setNotice("Shared with Kalena + Paris"); }); }, []);
  const nextDate = useMemo(() => { const dates = calendar.map(x => x.date || x.day).filter(x => /^\d{4}-\d{2}-\d{2}$/.test(x)).sort(); return dates.length ? plusDays(dates.at(-1), 1) : iso(new Date()); }, [calendar]);
  const alerts = useMemo(() => { const today = iso(new Date()); const out = []; for (let d = 0; d <= 3; d++) { const date = plusDays(today, d); const rows = calendar.filter(x => (x.date || x.day) === date && !/published|done/i.test(x.status || "")); if (!rows.length && d === 3) out.push(`Nothing is planned for ${date} — three days away.`); const li = rows.some(x => x.channel === "LinkedIn"); if (rows.length && !li && d === 3) out.push(`LinkedIn is missing from the plan for ${date} — three days away.`); } return out; }, [calendar]);
  async function persist(nextCalendar, nextCampaigns = campaigns) { setCalendar(nextCalendar); setCampaigns(nextCampaigns); setNotice("Saving…"); await fetch("/api/workspace", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ state: { calendar: nextCalendar, campaigns: nextCampaigns } }) }); setNotice("Saved to Bleuprint · just now"); }
  function generate(event) {
    event.preventDefault(); if (!sources.length) { setNotice("Upload source context before generating a campaign."); setTab("sources"); return; } const date = form.date || nextDate; const id = `campaign-${Date.now()}`; const theme = form.theme.trim();
    const igVideo = form.instagramFormat === "reel"; const shared = !form.separateTikTok;
    const outputs = { instagram: igVideo ? { type: "Reel", structure: ["Hook (0–2 sec)", "Proof or tension (2–8 sec)", "Payoff + next step"] } : { type: "Carousel", structure: ["Slide 1 · tension", "Slide 2 · context", "Slide 3 · proof", "Slide 4 · implication", "Slide 5 · next step"] }, tiktok: igVideo ? (shared ? null : { type: "Video", structure: ["TikTok-specific hook", "Native explanation", "Comment prompt"] }) : { type: "Carousel", structure: ["Cover", "Three proof cards", "Closing prompt"] }, linkedin: { type: "Post", structure: ["Operational observation", "What the weekly theme reveals", "One grounded takeaway", "Question"] } };
    const evidence = (sources.filter(x => x.is_record).length ? sources.filter(x => x.is_record) : sources).slice(0, 4).map(x => x.name);
    const campaign = { id, date, theme, objective: form.objective, outputs, evidence, assets: {}, copy: {}, createdBy: member.name, createdAt: new Date().toISOString() };
    const rows = [{ id: `${id}-ig`, date, day: date, channel: "Instagram", format: igVideo ? "reel" : "carousel", title: theme, time: "12:00 ET", status: "Draft", campaignId: id }];
    if (outputs.tiktok) rows.push({ id: `${id}-tt`, date, day: date, channel: "TikTok", format: outputs.tiktok.type.toLowerCase(), title: shared ? `${theme} · shared expression` : `${theme} · TikTok expression`, time: "19:00 ET", status: "Draft", campaignId: id });
    rows.push({ id: `${id}-li`, date: plusDays(date, -1), day: plusDays(date, -1), channel: "LinkedIn", format: "text", title: `${theme} · strategic context`, time: "08:30 ET", status: "Draft", campaignId: id });
    persist([...calendar, ...rows], [campaign, ...campaigns]); setActive(campaign); setForm(emptyCampaign); setAnalysis({ title: "Campaign-to-calendar check", findings: [`${rows.length} platform outputs created and placed immediately.`, igVideo && shared ? "Instagram Reel is the shared video; no duplicate TikTok workspace was created." : "TikTok has its own required production section.", "LinkedIn was placed one day earlier to frame the weekly idea."], sources: evidence });
  }
  function updateRow(id, key, value) { persist(calendar.map(row => row.id === id ? { ...row, [key]: value, ...(key === "date" ? { day: value } : {}) } : row)); }
  function removeRow(id) { persist(calendar.filter(row => row.id !== id)); }
  function exportCsv() { const cols = ["date","channel","format","title","time","status"]; const esc = value => `"${String(value || "").replaceAll('"','""')}"`; const csv = [cols.join(","), ...calendar.map(row => cols.map(c => esc(row[c])).join(","))].join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = "passport-content-calendar.csv"; a.click(); URL.revokeObjectURL(a.href); }
  async function importCsv(file) { if (!file) return; const text = await file.text(); const lines = text.trim().split(/\r?\n/); const parse = line => line.match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g).map(x => x.replace(/,$/, "").replace(/^"|"$/g, "").replaceAll('""','"')); const headers = parse(lines.shift()); const rows = lines.map((line, i) => Object.fromEntries(parse(line).map((v, j) => [headers[j], v]))).map((x, i) => ({ ...x, id: x.id || `import-${Date.now()}-${i}`, day: x.date })); await persist(rows); }
  async function upload(file) { if (!file) return null; setNotice(`Uploading ${file.name}…`); const data = new FormData(); data.append("file", file); const response = await fetch("/api/sources", { method: "POST", body: data }); const result = await response.json(); if (!response.ok) { setNotice(result.error || "Upload failed"); return null; } setSources(result.documents || []); setMismatches(result.mismatches || []); setNotice(`${file.name} stored, classified and indexed`); return result; }
  async function markRecord(id) { const response = await fetch("/api/sources", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); const result = await response.json(); if (response.ok) { setSources(result.documents || []); setMismatches(result.mismatches || []); setNotice("Document of record updated"); } }
  function saveCampaign(updated) { setActive(updated); persist(calendar, campaigns.map(item => item.id === updated.id ? updated : item)); }
  async function analyze() { const response = await fetch("/api/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ calendar, campaigns }) }); setAnalysis(await response.json()); }
  const sorted = [...calendar].sort((a,b) => String(a.date || a.day).localeCompare(String(b.date || b.day)) || (platformOrder[a.channel] || 9) - (platformOrder[b.channel] || 9));
  return <main className="studio-shell"><header className="studio-head"><a href="/admin">← Bleuprint</a><div><span>Passport · live content system</span><strong>{notice}</strong></div><nav>{["generator","calendar","sources","review"].map(x => <button className={tab === x ? "active" : ""} onClick={() => setTab(x)} key={x}>{x}</button>)}</nav></header>{alerts.length ? <aside className="studio-alerts">{alerts.map(x => <p key={x}>Ahead of schedule · {x}</p>)}</aside> : null}<section className="studio-body">
    {tab === "generator" && <><div className="studio-title"><span>Next expression</span><h1>Generate once.<br />Place the week immediately.</h1><p>Format changes the production workspace. The calendar is updated as soon as the campaign is generated.</p></div><div className="studio-split"><form className="studio-card studio-form" onSubmit={generate}><label>Weekly theme<input value={form.theme} onChange={e => setForm({...form,theme:e.target.value})} required placeholder="What is this week proving?" /></label><label>Objective<textarea value={form.objective} onChange={e => setForm({...form,objective:e.target.value})} placeholder="What should the audience understand or do?" /></label><div className="format-choice"><button type="button" className={form.instagramFormat === "carousel" ? "selected" : ""} onClick={() => setForm({...form,instagramFormat:"carousel"})}>Instagram carousel<small>Creates IG slides + TikTok carousel</small></button><button type="button" className={form.instagramFormat === "reel" ? "selected" : ""} onClick={() => setForm({...form,instagramFormat:"reel"})}>Instagram Reel<small>One shared video workspace by default</small></button></div><label className="checkline"><input type="checkbox" checked={form.separateTikTok} onChange={e => setForm({...form,separateTikTok:e.target.checked})} /> Instagram and TikTok need different executions this week</label><label>Instagram date<input type="date" value={form.date} min={iso(new Date())} onChange={e => setForm({...form,date:e.target.value})} placeholder={nextDate} /></label><button className="primary">Generate and place in calendar</button></form><div className="studio-card preview"><span>Routing logic</span><h2>{form.instagramFormat === "carousel" ? "Two visual carousels + LinkedIn" : form.separateTikTok ? "Two videos + LinkedIn" : "One shared video + LinkedIn"}</h2><ol><li>Instagram: {form.instagramFormat}</li><li>TikTok: {form.instagramFormat === "carousel" ? "carousel section" : form.separateTikTok ? "separate video section" : "uses the Reel; no duplicate section"}</li><li>LinkedIn: updates from the same weekly theme</li></ol><p>Next open placement: {form.date || nextDate}</p></div></div></>}
    {tab === "calendar" && <><div className="studio-title row"><div><span>Shared calendar</span><h1>The week, editable.</h1></div><div className="calendar-actions"><button onClick={exportCsv}>Open in Excel / Sheets</button><label>Import edited CSV<input type="file" accept=".csv,text/csv" onChange={e => importCsv(e.target.files?.[0])} /></label></div></div><div className="calendar-table">{sorted.map(row => <article key={row.id}><input type="date" value={row.date || (/^\d{4}-/.test(row.day) ? row.day : "")} onChange={e => updateRow(row.id,"date",e.target.value)} /><select value={row.channel} onChange={e => updateRow(row.id,"channel",e.target.value)}><option>Instagram</option><option>TikTok</option><option>LinkedIn</option></select><input value={row.format} onChange={e => updateRow(row.id,"format",e.target.value)} /><input className="wide" value={row.title} onChange={e => updateRow(row.id,"title",e.target.value)} /><select value={row.status || "Draft"} onChange={e => updateRow(row.id,"status",e.target.value)}>{["Draft","In approval","Approved","Scheduled","Published","Done"].map(x=><option key={x}>{x}</option>)}</select><button className="delete" onClick={() => removeRow(row.id)}>Delete</button></article>)}</div><button className="add-row" onClick={() => persist([...calendar,{id:`row-${Date.now()}`,date:nextDate,day:nextDate,channel:"Instagram",format:"reel",title:"New post",time:"12:00 ET",status:"Draft"}])}>+ Add post</button></>}
    {tab === "sources" && <SourcesPanel sources={sources} inputRef={uploadRef} upload={upload} markRecord={markRecord} />}
    {tab === "review" && <ReviewPanel mismatches={mismatches} analysis={analysis} analyze={analyze} />}
  </section>{active && <CampaignWorkspace campaign={active} close={() => setActive(null)} save={saveCampaign} upload={upload} />}</main>;
}

function SourcesPanel({ sources, inputRef, upload, markRecord }) {
  return <><div className="studio-title row"><div><span>Source inbox</span><h1>Upload. Classify. Confirm.</h1><p>Bleuprint extracts explicit text, suggests where it belongs, and waits for a human to select each document of record.</p></div><button className="primary compact" onClick={() => inputRef.current?.click()}>Upload source files</button><input ref={inputRef} hidden type="file" multiple onChange={async e => { for (const file of e.target.files) await upload(file); }} /></div><div className="source-grid">{sources.length ? sources.map(source => <article className="studio-card" key={source.id}><span>{source.document_type} → {source.destination}</span><h2>{source.name}</h2><p>{source.context?.summary?.slice(0, 180) || "Stored; text extraction is still required."}</p><small>{source.context?.assumption_policy}</small><button className={source.is_record ? "record active" : "record"} onClick={() => markRecord(source.id)}>{source.is_record ? "Document of record" : "Make document of record"}</button></article>) : <div className="studio-card"><h2>No uploaded context yet.</h2><p>Upload Passport source files before generating campaigns.</p></div>}</div></>;
}

function ReviewPanel({ mismatches, analysis, analyze }) {
  return <><div className="studio-title"><span>Mismatch review</span><h1>What needs judgment.</h1><p>Authority gaps and explicit value changes live here until a human resolves them.</p><button className="primary compact" onClick={analyze}>Check the content plan</button></div><div className="mismatch-list">{mismatches.length ? mismatches.map(item => <article className="studio-card" key={item.id}><span>{item.mismatch_type}</span><h2>{item.document_name}</h2><p>{item.detail}</p><small>{item.source_location}{item.record_name ? " · compared with " + item.record_name : ""}</small></article>) : <div className="studio-card"><h2>No open source mismatches.</h2><p>Select documents of record to establish the comparison baseline.</p></div>}{analysis ? <div className="studio-card"><h2>{analysis.title}</h2>{analysis.findings?.map(x => <p key={x}>{x}</p>)}</div> : null}</div></>;
}

function CampaignWorkspace({ campaign, close, save, upload }) {
  async function attach(key, file) { if (!file) return; const preview = URL.createObjectURL(file); const next = { ...campaign, assets: { ...campaign.assets, [key]: { name: file.name, preview, state: "uploading" } } }; save(next); const result = await upload(file); if (result) save({ ...next, assets: { ...next.assets, [key]: { name: file.name, preview, state: "stored" } } }); }
  function copy(key, value) { save({ ...campaign, copy: { ...campaign.copy, [key]: value } }); }
  const carousel = campaign.outputs.instagram.type === "Carousel";
  return <div className="campaign-layer" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section className="campaign-workspace"><header><div><span>Campaign · {campaign.date}</span><h1>{campaign.theme}</h1><p>Context: {(campaign.evidence || []).join(" · ")}</p></div><button onClick={close}>×</button></header><div className="campaign-columns"><OutputBlock title="Instagram" mode={carousel ? "carousel" : "video"} prefix="ig" campaign={campaign} attach={attach} copy={copy}/>{campaign.outputs.tiktok ? <OutputBlock title="TikTok" mode={campaign.outputs.tiktok.type === "Carousel" ? "carousel" : "video"} prefix="tt" campaign={campaign} attach={attach} copy={copy}/> : null}<article className="output-card"><span>LinkedIn · weekly context</span><textarea value={campaign.copy.li || ""} onChange={e => copy("li", e.target.value)} placeholder="Write the LinkedIn post from the approved weekly context…"/></article></div><footer><p>{carousel ? "Each carousel has its own image slots." : campaign.outputs.tiktok ? "Instagram and TikTok have separate video preloads this week." : "The Instagram Reel is the shared video source unless specified otherwise."}</p><button onClick={close}>Return to calendar</button></footer></section></div>;
}

function OutputBlock({ title, mode, prefix, campaign, attach, copy }) {
  if (mode === "video") return <article className="output-card"><span>{title} video</span><label className="video-preload">{campaign.assets[prefix + "Video"]?.preview ? <video controls src={campaign.assets[prefix + "Video"].preview}/> : <b>Preload video</b>}<input type="file" accept="video/*" onChange={e => attach(prefix + "Video", e.target.files?.[0])}/></label><textarea value={campaign.copy[prefix + "Script"] || ""} onChange={e => copy(prefix + "Script", e.target.value)} placeholder={title + " script / shot notes"}/><textarea value={campaign.copy[prefix + "Caption"] || ""} onChange={e => copy(prefix + "Caption", e.target.value)} placeholder={title + " caption"}/></article>;
  return <article className="output-card"><span>{title} carousel</span>{[0,1,2,3,4].map(i => <div className="slide-builder" key={i}><label>{campaign.assets[prefix + i]?.preview ? <img src={campaign.assets[prefix + i].preview} alt=""/> : <b>{i + 1}</b>}<input type="file" accept="image/*" onChange={e => attach(prefix + i, e.target.files?.[0])}/></label><textarea value={campaign.copy[prefix + i] || ""} onChange={e => copy(prefix + i, e.target.value)} placeholder={"Slide " + (i + 1) + " copy"}/></div>)}<textarea value={campaign.copy[prefix + "Caption"] || ""} onChange={e => copy(prefix + "Caption", e.target.value)} placeholder={title + " caption"}/></article>;
}
