"use client";
import { useEffect, useMemo, useRef, useState } from "react";

const emptyCampaign = { theme: "", objective: "", instagramFormat: "carousel", separateTikTok: false, date: "" };
const iso = date => new Date(date).toISOString().slice(0, 10);
const plusDays = (date, days) => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + days); return iso(next); };
const platformOrder = { Instagram: 1, TikTok: 2, LinkedIn: 3 };

export default function ContentStudio({ member }) {
  const [calendar, setCalendar] = useState([]), [campaigns, setCampaigns] = useState([]), [form, setForm] = useState(emptyCampaign);
  const [tab, setTab] = useState("generator"), [sources, setSources] = useState([]), [notice, setNotice] = useState("Loading shared system…");
  const [question, setQuestion] = useState(""), [answer, setAnswer] = useState(null), [analysis, setAnalysis] = useState(null);
  const uploadRef = useRef(null);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("tab"); if (["generator","calendar","sources","intelligence"].includes(requested)) setTab(requested); Promise.all([fetch("/api/workspace").then(r => r.json()), fetch("/api/sources").then(r => r.json())]).then(([workspace, docs]) => { setCalendar(workspace.state?.calendar || []); setCampaigns(workspace.state?.campaigns || []); setSources(docs.documents || []); setNotice("Shared with Kalena + Paris"); }); }, []);
  const nextDate = useMemo(() => { const dates = calendar.map(x => x.date || x.day).filter(x => /^\d{4}-\d{2}-\d{2}$/.test(x)).sort(); return dates.length ? plusDays(dates.at(-1), 1) : iso(new Date()); }, [calendar]);
  const alerts = useMemo(() => { const today = iso(new Date()); const out = []; for (let d = 0; d <= 3; d++) { const date = plusDays(today, d); const rows = calendar.filter(x => (x.date || x.day) === date && !/published|done/i.test(x.status || "")); if (!rows.length && d === 3) out.push(`Nothing is planned for ${date} — three days away.`); const li = rows.some(x => x.channel === "LinkedIn"); if (rows.length && !li && d === 3) out.push(`LinkedIn is missing from the plan for ${date} — three days away.`); } return out; }, [calendar]);
  async function persist(nextCalendar, nextCampaigns = campaigns) { setCalendar(nextCalendar); setCampaigns(nextCampaigns); setNotice("Saving…"); await fetch("/api/workspace", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ state: { calendar: nextCalendar, campaigns: nextCampaigns } }) }); setNotice("Saved to Bleuprint · just now"); }
  function generate(event) {
    event.preventDefault(); const date = form.date || nextDate; const id = `campaign-${Date.now()}`; const theme = form.theme.trim();
    const igVideo = form.instagramFormat === "reel"; const shared = !form.separateTikTok;
    const outputs = { instagram: igVideo ? { type: "Reel", structure: ["Hook (0–2 sec)", "Proof or tension (2–8 sec)", "Payoff + next step"] } : { type: "Carousel", structure: ["Slide 1 · tension", "Slide 2 · context", "Slide 3 · proof", "Slide 4 · implication", "Slide 5 · next step"] }, tiktok: igVideo ? (shared ? null : { type: "Video", structure: ["TikTok-specific hook", "Native explanation", "Comment prompt"] }) : { type: "Carousel", structure: ["Cover", "Three proof cards", "Closing prompt"] }, linkedin: { type: "Post", structure: ["Operational observation", "What the weekly theme reveals", "One grounded takeaway", "Question"] } };
    const campaign = { id, date, theme, objective: form.objective, outputs, createdBy: member.name, createdAt: new Date().toISOString() };
    const rows = [{ id: `${id}-ig`, date, day: date, channel: "Instagram", format: igVideo ? "reel" : "carousel", title: theme, time: "12:00 ET", status: "Draft", campaignId: id }];
    if (outputs.tiktok) rows.push({ id: `${id}-tt`, date, day: date, channel: "TikTok", format: outputs.tiktok.type.toLowerCase(), title: shared ? `${theme} · shared expression` : `${theme} · TikTok expression`, time: "19:00 ET", status: "Draft", campaignId: id });
    rows.push({ id: `${id}-li`, date: plusDays(date, -1), day: plusDays(date, -1), channel: "LinkedIn", format: "text", title: `${theme} · strategic context`, time: "08:30 ET", status: "Draft", campaignId: id });
    persist([...calendar, ...rows], [campaign, ...campaigns]); setForm(emptyCampaign); setAnalysis({ title: "Campaign-to-calendar check", findings: [`${rows.length} platform outputs created and placed immediately.`, igVideo && shared ? "Instagram Reel is the shared video; no duplicate TikTok workspace was created." : "TikTok has its own required production section.", "LinkedIn was placed one day earlier to frame the weekly idea."], sources: sources.slice(0, 3).map(x => x.name) });
  }
  function updateRow(id, key, value) { persist(calendar.map(row => row.id === id ? { ...row, [key]: value, ...(key === "date" ? { day: value } : {}) } : row)); }
  function removeRow(id) { persist(calendar.filter(row => row.id !== id)); }
  function exportCsv() { const cols = ["date","channel","format","title","time","status"]; const esc = value => `"${String(value || "").replaceAll('"','""')}"`; const csv = [cols.join(","), ...calendar.map(row => cols.map(c => esc(row[c])).join(","))].join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = "passport-content-calendar.csv"; a.click(); URL.revokeObjectURL(a.href); }
  async function importCsv(file) { if (!file) return; const text = await file.text(); const lines = text.trim().split(/\r?\n/); const parse = line => line.match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g).map(x => x.replace(/,$/, "").replace(/^"|"$/g, "").replaceAll('""','"')); const headers = parse(lines.shift()); const rows = lines.map((line, i) => Object.fromEntries(parse(line).map((v, j) => [headers[j], v]))).map((x, i) => ({ ...x, id: x.id || `import-${Date.now()}-${i}`, day: x.date })); await persist(rows); }
  async function upload(file) { if (!file) return; setNotice(`Uploading ${file.name}…`); const data = new FormData(); data.append("file", file); const response = await fetch("/api/sources", { method: "POST", body: data }); const result = await response.json(); if (!response.ok) { setNotice(result.error || "Upload failed"); return; } setSources(result.documents); setNotice(`${file.name} stored and indexed`); }
  async function ask(event) { event.preventDefault(); const response = await fetch("/api/ask", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question }) }); setAnswer(await response.json()); }
  async function analyze() { const response = await fetch("/api/analyze", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ calendar, campaigns }) }); setAnalysis(await response.json()); }
  const sorted = [...calendar].sort((a,b) => String(a.date || a.day).localeCompare(String(b.date || b.day)) || (platformOrder[a.channel] || 9) - (platformOrder[b.channel] || 9));
  return <main className="studio-shell"><header className="studio-head"><a href="/admin">← Bleuprint</a><div><span>Passport · live content system</span><strong>{notice}</strong></div><nav>{["generator","calendar","sources","intelligence"].map(x => <button className={tab === x ? "active" : ""} onClick={() => setTab(x)} key={x}>{x}</button>)}</nav></header>{alerts.length ? <aside className="studio-alerts">{alerts.map(x => <p key={x}>Ahead of schedule · {x}</p>)}</aside> : null}<section className="studio-body">
    {tab === "generator" && <><div className="studio-title"><span>Next expression</span><h1>Generate once.<br />Place the week immediately.</h1><p>Format changes the production workspace. The calendar is updated as soon as the campaign is generated.</p></div><div className="studio-split"><form className="studio-card studio-form" onSubmit={generate}><label>Weekly theme<input value={form.theme} onChange={e => setForm({...form,theme:e.target.value})} required placeholder="What is this week proving?" /></label><label>Objective<textarea value={form.objective} onChange={e => setForm({...form,objective:e.target.value})} placeholder="What should the audience understand or do?" /></label><div className="format-choice"><button type="button" className={form.instagramFormat === "carousel" ? "selected" : ""} onClick={() => setForm({...form,instagramFormat:"carousel"})}>Instagram carousel<small>Creates IG slides + TikTok carousel</small></button><button type="button" className={form.instagramFormat === "reel" ? "selected" : ""} onClick={() => setForm({...form,instagramFormat:"reel"})}>Instagram Reel<small>One shared video workspace by default</small></button></div><label className="checkline"><input type="checkbox" checked={form.separateTikTok} onChange={e => setForm({...form,separateTikTok:e.target.checked})} /> Instagram and TikTok need different executions this week</label><label>Instagram date<input type="date" value={form.date} min={iso(new Date())} onChange={e => setForm({...form,date:e.target.value})} placeholder={nextDate} /></label><button className="primary">Generate and place in calendar</button></form><div className="studio-card preview"><span>Routing logic</span><h2>{form.instagramFormat === "carousel" ? "Two visual carousels + LinkedIn" : form.separateTikTok ? "Two videos + LinkedIn" : "One shared video + LinkedIn"}</h2><ol><li>Instagram: {form.instagramFormat}</li><li>TikTok: {form.instagramFormat === "carousel" ? "carousel section" : form.separateTikTok ? "separate video section" : "uses the Reel; no duplicate section"}</li><li>LinkedIn: updates from the same weekly theme</li></ol><p>Next open placement: {form.date || nextDate}</p></div></div></>}
    {tab === "calendar" && <><div className="studio-title row"><div><span>Shared calendar</span><h1>The week, editable.</h1></div><div className="calendar-actions"><button onClick={exportCsv}>Open in Excel / Sheets</button><label>Import edited CSV<input type="file" accept=".csv,text/csv" onChange={e => importCsv(e.target.files?.[0])} /></label></div></div><div className="calendar-table">{sorted.map(row => <article key={row.id}><input type="date" value={row.date || (/^\d{4}-/.test(row.day) ? row.day : "")} onChange={e => updateRow(row.id,"date",e.target.value)} /><select value={row.channel} onChange={e => updateRow(row.id,"channel",e.target.value)}><option>Instagram</option><option>TikTok</option><option>LinkedIn</option></select><input value={row.format} onChange={e => updateRow(row.id,"format",e.target.value)} /><input className="wide" value={row.title} onChange={e => updateRow(row.id,"title",e.target.value)} /><select value={row.status || "Draft"} onChange={e => updateRow(row.id,"status",e.target.value)}>{["Draft","In approval","Approved","Scheduled","Published","Done"].map(x=><option key={x}>{x}</option>)}</select><button className="delete" onClick={() => removeRow(row.id)}>Delete</button></article>)}</div><button className="add-row" onClick={() => persist([...calendar,{id:`row-${Date.now()}`,date:nextDate,day:nextDate,channel:"Instagram",format:"reel",title:"New post",time:"12:00 ET",status:"Draft"}])}>+ Add post</button></>}
    {tab === "sources" && <><div className="studio-title row"><div><span>Live memory</span><h1>Upload Passport again.</h1><p>Start from source files instead of trusting the demonstration data. <a href="/hq/passport/week-one.html" target="_blank">Open the current Week One record ↗</a></p></div><button className="primary compact" onClick={() => uploadRef.current?.click()}>Upload source files</button><input ref={uploadRef} hidden type="file" multiple onChange={async e => { for (const file of e.target.files) await upload(file); }} /></div><div className="source-grid">{sources.length ? sources.map(source => <article className="studio-card" key={source.pathname}><span>{source.extraction_state}</span><h2>{source.name}</h2><p>{Math.round(source.size_bytes/1024)} KB · uploaded by {source.uploaded_by}</p></article>) : <div className="studio-card"><h2>No uploaded sources yet.</h2><p>HTML, text, Markdown, CSV and JSON are indexed immediately. Other documents are stored safely for the extraction connector.</p></div>}</div></>}
    {tab === "intelligence" && <><div className="studio-title"><span>Evidence, not theater</span><h1>Ask and analyze<br />against what exists.</h1><p>Answers cite uploaded sources. Analyze checks calendar coverage, platform routing and missing context.</p></div><div className="studio-split"><form className="studio-card studio-form" onSubmit={ask}><label>Ask Bleuprint<textarea value={question} onChange={e=>setQuestion(e.target.value)} required placeholder="What does Passport say about claims?" /></label><button className="primary">Search live memory</button>{answer && <div className="result"><h2>{answer.answer}</h2>{answer.citations?.map(x=><p key={x.name}><b>{x.name}</b> · {x.excerpt}</p>)}</div>}</form><div className="studio-card"><span>Analyze use case</span><h2>Find what will get missed before production.</h2><p>Checks missing LinkedIn support, duplicated or absent TikTok executions, empty days, source coverage and orphaned campaign outputs.</p><button className="primary" onClick={analyze}>Analyze this week</button>{analysis && <div className="result"><h2>{analysis.title}</h2>{analysis.findings?.map(x=><p key={x}>{x}</p>)}{analysis.sources?.length ? <small>Sources: {analysis.sources.join(" · ")}</small> : null}</div>}</div></div></>}
  </section></main>;
}
