"use client";

import { SignOutButton, UserButton } from "@clerk/nextjs";
import { useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "bleuprint-operating-system-v1";
const initialState = {
  decisions: [
    { id: "d1", title: "Choose the color system of record", owner: "Kalena + Paris", due: "Sep 8", status: "open", impact: "Blocks repeatable asset generation." },
    { id: "d2", title: "Confirm the typeface on record", owner: "Paris", due: "Sep 8", status: "open", impact: "Controls every generated visual." },
    { id: "d3", title: "Define permanent use of Contour Gold", owner: "Kalena + Paris", due: "Sep 8", status: "open", impact: "Separates brand structure from decoration." },
    { id: "d4", title: "Keep a human approval before publishing", owner: "Kalena", due: "Active rule", status: "decided", impact: "Protects proof, voice, and accountability." },
    { id: "d5", title: "Keep founder, pipeline, architecture and investor details in stealth", owner: "Kalena + Paris", due: "Review weekly", status: "decided", impact: "Defines what automation may not disclose." }
  ],
  tasks: [
    { id: "t1", phase: "Align the story", title: "Paris signs off the brand guide", owner: "Paris", due: "Sep 8", done: false, priority: true },
    { id: "t2", phase: "Align the story", title: "Publish the standalone go-to-market document", owner: "Kalena", due: "Sep 8", done: false },
    { id: "t3", phase: "Align the story", title: "Audit Instagram, TikTok and LinkedIn profiles", owner: "Kalena", due: "Sep 8", done: false },
    { id: "t4", phase: "Paperwork", title: "Complete business plan v1", owner: "Kalena", due: "Sep 8", done: false },
    { id: "t5", phase: "Paperwork", title: "Put entity and cap table on paper", owner: "Both", due: "Sep 9", done: false, priority: true },
    { id: "t6", phase: "Paperwork", title: "Create financial model with runway and ask", owner: "Both", due: "Sep 9", done: false },
    { id: "t7", phase: "Capital", title: "Launch grant and capital tracker", owner: "Kalena", due: "Sep 10", done: false },
    { id: "t8", phase: "Capital", title: "Line up one or two design partners", owner: "Both", due: "Sep 20", done: false, priority: true },
    { id: "t9", phase: "Attention", title: "Start recording the founder documentary", owner: "Both", due: "Now", done: false, priority: true },
    { id: "t10", phase: "Attention", title: "Set footage consent and naming conventions", owner: "Kalena", due: "Sep 9", done: false },
    { id: "t11", phase: "Attention", title: "Build the AI governance press list", owner: "Kalena", due: "Sep 15", done: false },
    { id: "t12", phase: "Operating rhythm", title: "Run the Friday evidence review", owner: "Both", due: "Friday", done: false }
  ],
  content: [
    { id: "c1", title: "Do you trust your AI agents?", pillar: "Teaser arc", proof: "No claim", platforms: "Instagram · TikTok", status: "draft", source: "Live mark animation" },
    { id: "c2", title: "The model proposes. Passport decides.", pillar: "Permission gap", proof: "Scenario", platforms: "LinkedIn", status: "draft", source: "Brand guide positioning" },
    { id: "c3", title: "Who decided its refund limit?", pillar: "Bounded authority", proof: "Scenario", platforms: "Instagram · TikTok", status: "draft", source: "Motion-card brief" },
    { id: "c4", title: "The missing layer in an agent incident", pillar: "Accountability", proof: "Sourced report", platforms: "LinkedIn", status: "blocked", source: "Outlet and date required" },
    { id: "c5", title: "Five bounds every agent permission needs", pillar: "Bounded authority", proof: "Scenario", platforms: "LinkedIn", status: "draft", source: "Brand strategy" }
  ],
  opportunities: [
    { id: "o1", title: "Secure one design-partner conversation before accelerator applications", type: "Relationship", urgency: "This month", status: "act", why: "External evidence strengthens both product learning and applications." },
    { id: "o2", title: "Turn the public verifier into a developer-channel launch", type: "Distribution", urgency: "Sep 20", status: "investigate", why: "Showing the tool fits the quiet, technically credible voice." },
    { id: "o3", title: "Reuse documentary footage for the YC founder video", type: "Leverage", urgency: "Before application", status: "watch", why: "One capture creates multiple useful assets." }
  ]
};
const nav = ["Today", "Passport", "Decisions", "Work", "Content", "Opportunities", "Friday review"];

function Mark() { return <span className="bp-mark" aria-hidden="true"><i /><i /><i /><i /><b /></span>; }
function statusLabel(s) { return ({ approved:"Approved", blocked:"Blocked", decided:"Decided", act:"Act", investigate:"Investigate", watch:"Watch", open:"Open" })[s] || "Draft"; }
function PageHead({ kicker, title, lede }) { return <div className="page-head"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{lede}</p></div>; }

export default function OperatingSystem({ firstName }) {
  const [section, setSection] = useState("Today");
  const [data, setData] = useState(initialState);
  const [loaded, setLoaded] = useState(false);
  const [opportunity, setOpportunity] = useState("");
  useEffect(() => { try { const saved = localStorage.getItem(STORAGE_KEY); if (saved) setData(JSON.parse(saved)); } catch {} setLoaded(true); }, []);
  useEffect(() => { if (loaded) localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }, [data, loaded]);
  const metrics = useMemo(() => ({ openDecisions:data.decisions.filter(x=>x.status==="open").length, completeTasks:data.tasks.filter(x=>x.done).length, approvedContent:data.content.filter(x=>x.status==="approved").length, activeOpportunities:data.opportunities.length }), [data]);
  const toggleTask = id => setData(s => ({...s,tasks:s.tasks.map(x=>x.id===id?{...x,done:!x.done}:x)}));
  const toggleDecision = id => setData(s => ({...s,decisions:s.decisions.map(x=>x.id===id?{...x,status:x.status==="decided"?"open":"decided"}:x)}));
  const toggleContent = id => setData(s => ({...s,content:s.content.map(x=>x.id===id&&x.status!=="blocked"?{...x,status:x.status==="approved"?"draft":"approved"}:x)}));
  function addOpportunity(e){ e.preventDefault(); const title=opportunity.trim(); if(!title)return; setData(s=>({...s,opportunities:[{id:`o${Date.now()}`,title,type:"New signal",urgency:"Review Friday",status:"investigate",why:"Newly captured; connect evidence and choose an owner during review."},...s.opportunities]})); setOpportunity(""); }
  return <main className="os-shell"><aside className="os-rail"><button className="os-brand" onClick={()=>setSection("Today")}><Mark/><span>Bleuprint<small>Operating system</small></span></button><nav>{nav.map(x=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)}>{x}</button>)}</nav><div className="os-user"><UserButton/><span>{firstName}<small>Strategy lead</small></span><SignOutButton><button className="text-button">Sign out</button></SignOutButton></div></aside><section className="os-main"><header className="os-topbar"><div><span className="eyebrow">Passport · first client</span><strong>{section}</strong></div><div className="os-health"><span className="pulse"/> Operating record active</div></header>{section==="Today"&&<Today data={data} metrics={metrics} setSection={setSection} toggleTask={toggleTask}/>} {section==="Passport"&&<Passport/>} {section==="Decisions"&&<Decisions items={data.decisions} toggle={toggleDecision}/>} {section==="Work"&&<Work items={data.tasks} toggle={toggleTask}/>} {section==="Content"&&<Content items={data.content} toggle={toggleContent}/>} {section==="Opportunities"&&<Opportunities items={data.opportunities} value={opportunity} setValue={setOpportunity} add={addOpportunity}/>} {section==="Friday review"&&<Review data={data} metrics={metrics}/>}</section></main>;
}

function Today({data,metrics,setSection,toggleTask}){const priority=data.tasks.filter(x=>!x.done&&x.priority).slice(0,4);return <div className="os-page"><PageHead kicker="Monday · September 7" title="The next move, without losing the why." lede="Passport is the first live proof of the Bleuprint method: evidence becomes a decision, the decision becomes sequenced work, and the work produces a measurable signal."/><div className="metric-grid"><button onClick={()=>setSection("Decisions")}><span>Open decisions</span><strong>{metrics.openDecisions}</strong><small>Resolve before automation</small></button><button onClick={()=>setSection("Work")}><span>Work complete</span><strong>{metrics.completeTasks}/{data.tasks.length}</strong><small>Shared operating record</small></button><button onClick={()=>setSection("Content")}><span>Approved content</span><strong>{metrics.approvedContent}/{data.content.length}</strong><small>Human gate remains active</small></button><button onClick={()=>setSection("Opportunities")}><span>Signals to review</span><strong>{metrics.activeOpportunities}</strong><small>Nothing useful disappears</small></button></div><div className="split-grid"><section className="os-panel"><div className="panel-head"><div><span className="eyebrow">Now</span><h2>Priority work</h2></div><button onClick={()=>setSection("Work")}>View all</button></div><div className="task-list">{priority.map(x=><button key={x.id} className="task-row" onClick={()=>toggleTask(x.id)}><span className={`check ${x.done?"done":""}`}>{x.done?"✓":""}</span><span><strong>{x.title}</strong><small>{x.owner} · {x.due}</small></span></button>)}</div></section><section className="os-panel attention"><span className="eyebrow">Attention brief</span><h2>What could get missed</h2><ul><li>The content engine cannot be trusted until the three visual decisions are settled.</li><li>Thursday’s sourced-report post is blocked until the outlet and publication date are recorded.</li><li>Design-partner evidence is more valuable right now than another week of polished launch content.</li><li>Documentary footage compounds only if consent, naming and backup begin on day one.</li></ul></section></div></div>}
function Passport(){return <div className="os-page"><PageHead kicker="Client record · Passport" title="The permission layer for agents." lede="Passport makes every AI agent identifiable, verifiable and accountable before it is allowed to act."/><div className="strategy-grid"><section className="os-panel span-two"><span className="eyebrow">Positioning</span><blockquote>The model proposes. Passport decides.</blockquote><p>Authorization and evidence infrastructure that binds an agent to an owner, a bounded capability, a policy decision and verifiable proof.</p></section><section className="os-panel"><span className="eyebrow">Audience</span><h2>Teams deploying agents into sensitive workflows</h2><p>Technical, security, compliance and operational leaders who need speed without losing human authority.</p></section><section className="os-panel"><span className="eyebrow">Never claim</span><h2>No borrowed certainty</h2><p>Not generic IAM. Not proof of humanity. Not “unhackable.” Never promise zero risk.</p></section><section className="os-panel span-two"><span className="eyebrow">Proof ladder</span><div className="proof-ladder">{["Sourced report","Scenario","Lab demonstration","Design-partner result","Customer case"].map((x,i)=><div key={x}><small>0{i}</small><strong>{x}</strong></div>)}</div></section><section className="os-panel guardrail"><span className="eyebrow">Stealth boundary</span><h2>Do not disclose</h2><p>Founders, pipeline, non-public architecture, security details, unannounced partnerships or investor names.</p></section></div></div>}
function Decisions({items,toggle}){return <div className="os-page"><PageHead kicker="Source of truth" title="Decisions, not competing drafts." lede="A decision remains visible with its owner, consequence and status so future work does not reconstruct strategy from memory."/><div className="record-list">{items.map(x=><button className="record" key={x.id} onClick={()=>toggle(x.id)}><span className={`status ${x.status}`}>{statusLabel(x.status)}</span><span className="record-copy"><strong>{x.title}</strong><small>{x.impact}</small></span><span className="record-meta">{x.owner}<small>{x.due}</small></span></button>)}</div></div>}
function Work({items,toggle}){const phases=[...new Set(items.map(x=>x.phase))];return <div className="os-page"><PageHead kicker="Sequenced execution" title="Work connected to strategy." lede="Every item has an owner, a reason and a place in the operating sequence."/>{phases.map(p=><section className="phase" key={p}><div className="phase-title"><span className="eyebrow">Phase</span><h2>{p}</h2><small>{items.filter(x=>x.phase===p&&x.done).length}/{items.filter(x=>x.phase===p).length} complete</small></div><div className="task-list">{items.filter(x=>x.phase===p).map(x=><button key={x.id} className={`task-row ${x.done?"finished":""}`} onClick={()=>toggle(x.id)}><span className={`check ${x.done?"done":""}`}>{x.done?"✓":""}</span><span><strong>{x.title}</strong><small>{x.owner} · {x.due}</small></span>{x.priority&&<em>Priority</em>}</button>)}</div></section>)}</div>}
function Content({items,toggle}){return <div className="os-page"><PageHead kicker="Content operations" title="One idea. Platform-specific expression." lede="Every post stays connected to a pillar, proof level, source and human approval."/><div className="content-grid">{items.map(x=><article className={`content-card ${x.status}`} key={x.id}><div className="content-top"><span className={`status ${x.status}`}>{statusLabel(x.status)}</span><small>{x.platforms}</small></div><h2>{x.title}</h2><dl><div><dt>Pillar</dt><dd>{x.pillar}</dd></div><div><dt>Proof</dt><dd>{x.proof}</dd></div><div><dt>Source</dt><dd>{x.source}</dd></div></dl><button disabled={x.status==="blocked"} onClick={()=>toggle(x.id)}>{x.status==="approved"?"Return to draft":x.status==="blocked"?"Resolve missing evidence first":"Approve for publishing"}</button></article>)}</div></div>}
function Opportunities({items,value,setValue,add}){return <div className="os-page"><PageHead kicker="Opportunity radar" title="Notice the signal before it disappears." lede="Capture relationships, distribution openings, deadlines and useful patterns before deciding whether to act."/><form className="capture" onSubmit={add}><label htmlFor="signal">Capture a new signal</label><div><input id="signal" value={value} onChange={e=>setValue(e.target.value)} placeholder="What did you notice?"/><button>Add to Friday review</button></div></form><div className="opportunity-list">{items.map(x=><article key={x.id}><div><span className={`status ${x.status}`}>{statusLabel(x.status)}</span><small>{x.type} · {x.urgency}</small></div><h2>{x.title}</h2><p>{x.why}</p></article>)}</div></div>}
function Review({data,metrics}){const blocked=data.content.filter(x=>x.status==="blocked"),priorities=data.tasks.filter(x=>x.priority&&!x.done);return <div className="os-page"><PageHead kicker="Weekly operating rhythm" title="Friday evidence review." lede="Thirty minutes to decide what changed, what matters now and what will move during the next two weeks."/><div className="review-grid"><section className="os-panel"><span className="eyebrow">Progress</span><h2>{metrics.completeTasks} tasks completed</h2><p>{metrics.approvedContent} content records approved. {metrics.openDecisions} decisions remain open.</p></section><section className="os-panel"><span className="eyebrow">Blocked</span><h2>{blocked.length||"No"} content item{blocked.length===1?"":"s"}</h2><p>{blocked.map(x=>x.title).join(", ")||"No current publishing blockers."}</p></section><section className="os-panel span-two"><span className="eyebrow">Carry into the next sprint</span><ol>{priorities.map(x=><li key={x.id}><strong>{x.title}</strong><span>{x.owner} · {x.due}</span></li>)}</ol></section><section className="os-panel span-two"><span className="eyebrow">Questions for the room</span><ol><li><strong>What evidence changed our view?</strong><span>Performance, conversations, objections or new category signals.</span></li><li><strong>What are we doing that no longer serves the constraint?</strong><span>Drop it deliberately rather than carrying it invisibly.</span></li><li><strong>What deserves a decision, owner or automation?</strong><span>Convert every useful observation into a record.</span></li></ol></section></div></div>}
