"use client";

import { useMemo, useRef, useState } from "react";

const OWNER = { K: "Kalena", P: "Paris", Both: "Kalena + Paris" };
const proofLabels = ["Scenario", "Lab demonstration", "Sourced report", "Design partner result", "Customer case", "No claim"];
const sourceHref = source => source.pathname?.startsWith("db://passport/bundled/") ? `/hq/passport/${source.name}` : `/api/sources/${source.id}/file`;

export function WorkspaceModal({ title, kicker, children, close, wide = false, actions = null }) {
  return <div className="workspace-layer" onMouseDown={event => event.target === event.currentTarget && close()}>
    <section className={`workspace-modal${wide ? " wide" : ""}`}>
      <header><div><small>{kicker}</small><h1>{title}</h1></div><div className="workspace-head-actions">{actions}<button className="round-close" onClick={close} aria-label="Close">×</button></div></header>
      <div className="workspace-scroll">{children}</div>
    </section>
  </div>;
}

export function MemoryPanel({ sources, mismatches, onUpload, onRefresh, onUpdate, status }) {
  const filesRef = useRef(null), folderRef = useRef(null);
  const [editing, setEditing] = useState(null), [draft, setDraft] = useState({ summary:"", document_type:"", destination:"" });
  async function chosen(list) { for (const file of Array.from(list || [])) await onUpload(file); onRefresh(); }
  return <div className="memory-workspace"><section className="memory-intro"><div><span>What Bleuprint knows</span><h2>{sources.length} source{sources.length === 1 ? "" : "s"} in Passport memory</h2><p>Add the Passport folder once, then add changed or new files as the brand develops. Bleuprint extracts explicit context and never silently turns an assumption into a decision.</p></div><div className="memory-upload-actions"><button onClick={() => folderRef.current?.click()}>Import Passport folder</button><button onClick={() => filesRef.current?.click()}>Add files</button><input ref={filesRef} hidden multiple type="file" onChange={event => chosen(event.target.files)} /><input ref={folderRef} hidden multiple type="file" webkitdirectory="" onChange={event => chosen(event.target.files)} /></div></section>
    <p className="workspace-status">{status}</p>
    {mismatches.length ? <section className="memory-signals"><span>{mismatches.length} NEED JUDGMENT</span>{mismatches.slice(0,4).map(item => <p key={item.id}><b>{item.document_name}</b> · {item.detail} <em>{item.source_location}</em></p>)}</section> : null}
    <section className="memory-records">{sources.length ? sources.map(source => <article key={source.id} className={source.is_record ? "is-record" : ""}><div className="memory-meta"><span>{source.document_type}</span><small>{source.destination}</small></div><h3><a href={sourceHref(source)} target="_blank" rel="noreferrer">{source.name}</a></h3>{editing === source.id ? <div className="memory-edit"><textarea value={draft.summary} onChange={event => setDraft(current=>({...current,summary:event.target.value}))} /><input aria-label="Document type" value={draft.document_type} onChange={event=>setDraft(current=>({...current,document_type:event.target.value}))}/><input aria-label="Destination" value={draft.destination} onChange={event=>setDraft(current=>({...current,destination:event.target.value}))}/><button onClick={async () => { await onUpdate(source.id,{ summary:draft.summary, document_type:draft.document_type, destination:draft.destination }); setEditing(null); }}>Save memory</button><button onClick={() => setEditing(null)}>Cancel</button></div> : <p>{source.context?.summary?.slice(0,420) || "Stored. Text extraction is not available for this format yet."}</p>}<footer><a href={sourceHref(source)} target="_blank" rel="noreferrer">Open source ↗</a><button onClick={() => { setEditing(source.id); setDraft({summary:source.context?.summary || "",document_type:source.document_type || "reference",destination:source.destination || "Source inbox"}); }}>Edit memory</button><button className={source.is_record ? "confirmed" : ""} onClick={() => onUpdate(source.id,{ markRecord:true })}>{source.is_record ? "Reconfirm record" : "Confirm as record"}</button></footer></article>) : <div className="empty-workspace"><h3>Start with the Passport folder.</h3><p>Upload brand-guide.html, roadmap.html, week-one.html, and index.html. Add strategy, research, analytics, and final assets afterward.</p></div>}</section>
  </div>;
}

export function RoadmapPanel({ roadmap, onSave, onUpload, onOpenContent, member }) {
  const [filter, setFilter] = useState("open");
  const state = roadmap?.state || { done:{}, blocked:{}, questions:{} };
  const phases = roadmap?.phases || [];
  const all = phases.flatMap(phase => phase.tasks.map(task => ({ ...task, phase:phase.name })));
  const doneCount = all.filter(task => state.done?.[task.id]).length;
  function update(next) { onSave({ done: state.done || {}, blocked: state.blocked || {}, questions: state.questions || {}, attachments: state.attachments || {}, ...next }); }
  function toggle(task) { update({ done:{ ...(state.done || {}), [task.id]:!state.done?.[task.id] } }); }
  function question(task, value) { if (value !== (state.questions?.[task.id] || "")) update({ questions:{ ...(state.questions || {}), [task.id]:value } }); }
  function blocked(task) { const next={ ...(state.blocked || {}) }; if(next[task.id]) delete next[task.id]; else next[task.id]={ by:member.name, at:new Date().toISOString() }; update({ blocked:next }); }
  async function attach(task, file) { if(!file)return; const doc=await onUpload(file); if(!doc)return; update({ attachments:{ ...(state.attachments || {}), [task.id]:[...(state.attachments?.[task.id] || []),{id:doc.id,name:doc.name}] } }); }
  return <div className="roadmap-workspace"><section className="roadmap-summary"><div><span>SHARED ROADMAP</span><strong>{doneCount}</strong><small>of {all.length} complete</small></div><p>The roadmap is the operating order. Questions identify missing documents or decisions; bottlenecks stay visible until a person resolves them.</p><nav>{["open","bottlenecks","done","all"].map(item => <button className={filter===item?"active":""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</nav></section>{phases.map(phase => { const visible=phase.tasks.filter(task => filter==="all" || (filter==="done"&&state.done?.[task.id]) || (filter==="bottlenecks"&&state.blocked?.[task.id]) || (filter==="open"&&!state.done?.[task.id])); return visible.length ? <section className="roadmap-phase" key={phase.id}><header><span>{phase.number}</span><div><h2>{phase.name}</h2><p>{phase.why}</p></div><small>{phase.when}</small></header>{visible.map(task => <article key={task.id} className={`${state.done?.[task.id]?"done ":""}${state.blocked?.[task.id]?"blocked":""}`}><button className="roadmap-check" onClick={() => toggle(task)} aria-label={`Mark ${task.title} ${state.done?.[task.id]?"open":"done"}`}>{state.done?.[task.id]?"✓":""}</button><div><h3>{task.title}{task.key?<b>KEY</b>:null}</h3><p>{task.detail}</p>{state.attachments?.[task.id]?.length?<div className="roadmap-attachments">{state.attachments[task.id].map(file=><a key={file.id} href={`/api/sources/${file.id}/file`} target="_blank" rel="noreferrer">{file.name} ↗</a>)}</div>:null}<textarea defaultValue={state.questions?.[task.id] || ""} onBlur={event => question(task,event.target.value)} placeholder="Add a team question, missing document, or decision…" /></div><aside><span>{OWNER[task.owner] || task.owner}</span><small>{task.due}</small><button onClick={() => blocked(task)}>{state.blocked?.[task.id]?"Clear bottleneck":"Flag bottleneck"}</button><label className="roadmap-attach">Attach file<input hidden type="file" onChange={event=>attach(task,event.target.files?.[0])}/></label>{/content|post|social|campaign/i.test(task.title)?<button onClick={onOpenContent}>Open content</button>:null}</aside></article>)}</section> : null; })}</div>;
}

export function ContentPanel({ calendar, campaigns, onSave, onUpload, onAnalyze, analysis, status }) {
  const [channel, setChannel] = useState("Instagram"), [activeId, setActiveId] = useState(null);
  const rows = useMemo(() => calendar.filter(row => row.channel === channel), [calendar, channel]);
  const active = calendar.find(row => row.id === activeId);
  function updateRow(id, changes) { onSave(calendar.map(row => row.id === id ? { ...row, ...changes } : row), campaigns); }
  if (active) return <CampaignPanel row={active} calendar={calendar} campaigns={campaigns} back={() => setActiveId(null)} save={(nextCampaign,nextRows=calendar) => onSave(nextRows, [nextCampaign,...campaigns.filter(item=>item.id!==nextCampaign.id)])} upload={onUpload} analyze={onAnalyze} analysis={analysis} />;
  return <div className="content-workspace"><section className="content-overview"><div><span>CONTENT / CURRENT CALENDAR</span><h2>One week. Three expressions.</h2><p>Select the planned post first. The campaign workspace will use its format, proof requirement, source material, and scheduled platform.</p></div><button onClick={() => rows[0] && setActiveId(rows[0].id)} disabled={!rows.length}>Open next {channel} post</button></section><nav className="platform-tabs">{["Instagram","TikTok","LinkedIn"].map(item => <button key={item} onClick={() => setChannel(item)} className={channel===item?"active":""}>{item}<small>{calendar.filter(row=>row.channel===item).length}</small></button>)}</nav><section className="content-list">{rows.length ? rows.map(row => <article key={row.id}><button className="content-open" onClick={() => setActiveId(row.id)}><span>{row.date || row.day}</span><h3>{row.title}</h3><p>{row.format} · {row.time}</p></button><select value={row.status || "Draft"} onChange={event => updateRow(row.id,{status:event.target.value})}>{["Draft","In approval","Approved","Scheduled","Published","Done","Blocked"].map(item=><option key={item}>{item}</option>)}</select></article>) : <div className="empty-workspace"><h3>No {channel} posts in this calendar.</h3><p>Import a content calendar through Memory or add this platform to the weekly plan.</p></div>}</section><footer className="content-foot"><span>{status}</span><button onClick={() => onAnalyze(calendar,campaigns)}>Check the whole week</button></footer>{analysis ? <AlignmentResults analysis={analysis} /> : null}</div>;
}

function blankOutput(row) { return { format:row.format || "post", proof:row.proof || "", caption:row.captionA || row.copy || "", alternate:row.captionB || "", script:row.script || row.screen || "", brief:row.brief || "", assets:[], slides:Array.from({length:/carousel/i.test(row.format||"")?5:0},()=>({copy:"",asset:null})) }; }

function CampaignPanel({ row, calendar, campaigns, back, save, upload, analyze, analysis }) {
  const campaignKey = row.campaignKey || row.campaignId || row.id;
  const related = calendar.filter(item => item.id === row.id || (item.campaignKey || item.campaignId) === campaignKey);
  const campaignId = `campaign-${campaignKey}`;
  const existing = campaigns.find(item => item.id === campaignId || item.id === `post-${row.id}`);
  const initial = existing || { id:campaignId, calendarId:row.id, calendarIds:related.map(item=>item.id), campaignKey, title:row.title, week:row.week || "Current week", status:row.status || "Draft", outputs:Object.fromEntries(related.map(item=>[item.channel,{...blankOutput(item),calendarId:item.id}])) };
  const [campaign,setCampaign] = useState(initial), [platform,setPlatform] = useState(row.channel), [saving,setSaving] = useState("");
  const output = campaign.outputs[platform] || blankOutput(row);
  function change(changes) { setCampaign(current => ({ ...current, outputs:{...current.outputs,[platform]:{...output,...changes}} })); }
  async function attach(file, slideIndex=null) { if(!file)return; setSaving(`Storing ${file.name}…`); const doc=await upload(file); if(!doc){setSaving("Upload failed");return;} const asset={id:doc.id,name:doc.name,type:doc.content_type}; if(slideIndex===null) change({assets:[...(output.assets||[]),asset]}); else {const slides=[...(output.slides||[])]; slides[slideIndex]={...slides[slideIndex],asset}; change({slides});} setSaving(`${file.name} shared with the team`); }
  function store(status=campaign.status) { const next={...campaign,status,updatedAt:new Date().toISOString()}; setCampaign(next); const relatedIds=new Set(related.map(item=>item.id)); const nextRows=calendar.map(item=>relatedIds.has(item.id)?{...item,status,campaignId:next.id,campaignKey}:item); save(next,nextRows); setSaving("Saved to the shared Passport workspace"); }
  return <div className="campaign-production"><button className="back-button" onClick={back}>← Back to calendar</button><header><div><span>{campaign.week} / CAMPAIGN</span><h2>{campaign.title}</h2><p>{row.date || row.day} · generated from this calendar post, not from a blank prompt.</p></div><div><button onClick={() => store("Draft")}>Save</button><button className="approve" onClick={() => store("Approved")}>Approve + update calendar</button></div></header><nav className="platform-tabs">{Object.keys(campaign.outputs).map(item=><button className={platform===item?"active":""} key={item} onClick={()=>setPlatform(item)}>{item}</button>)}</nav><section className="production-grid"><article><span>Direction</span><label>Brief<textarea value={output.brief||""} onChange={event=>change({brief:event.target.value})}/></label><label>Proof label<select value={output.proof||""} onChange={event=>change({proof:event.target.value})}><option value="">Select the evidence level</option>{proofLabels.map(item=><option key={item}>{item}</option>)}</select></label><label>Script / on-screen direction<textarea value={output.script||""} onChange={event=>change({script:event.target.value})}/></label></article><article><span>Copy</span><label>Primary copy<textarea className="tall" value={output.caption||""} onChange={event=>change({caption:event.target.value})}/></label><label>Alternate<textarea value={output.alternate||""} onChange={event=>change({alternate:event.target.value})}/></label></article><article><span>{/carousel/i.test(output.format)?"Carousel build":"Media"}</span>{/carousel/i.test(output.format)?<div className="slide-stack">{output.slides.map((slide,index)=><div key={index}><label className="asset-drop">{slide.asset?.name||`Add image ${index+1}`}<input type="file" accept="image/*" onChange={event=>attach(event.target.files?.[0],index)}/></label><textarea value={slide.copy||""} onChange={event=>{const slides=[...output.slides];slides[index]={...slide,copy:event.target.value};change({slides});}} placeholder={`Slide ${index+1} copy`}/></div>)}</div>:<><label className="asset-drop large">Add or replace {platform === "LinkedIn" ? "supporting asset" : "video / cover"}<input type="file" accept="image/*,video/*" onChange={event=>attach(event.target.files?.[0])}/></label>{output.assets?.map(asset=><p className="asset-name" key={asset.id}>{asset.name}</p>)}</>}</article></section><footer><span>{saving}</span><button onClick={()=>analyze(calendar,[campaign,...campaigns.filter(item=>item.id!==campaign.id)])}>Check alignment</button></footer>{analysis?<AlignmentResults analysis={analysis}/>:null}</div>;
}

export function AlignmentResults({ analysis }) {
  const findings=analysis?.checks||analysis?.findings||[];
  return <section className="alignment-results"><header><span>ALIGNMENT CHECK</span><h3>{analysis?.title || "What needs attention"}</h3></header>{findings.map((finding,index)=>typeof finding==="string"?<article key={index}><b>Review</b><p>{finding}</p></article>:<article key={finding.id||index} className={finding.severity||"review"}><b>{finding.severity||"review"}</b><div><h4>{finding.title||finding.message}</h4>{finding.message&&finding.title?<p>{finding.message}</p>:null}<small>{finding.affectedOutput||finding.output||"Workspace"} · {finding.evidenceDocument||"Passport memory"}{finding.evidenceLocation?` · ${finding.evidenceLocation}`:""}</small><em>{finding.recommendation}</em></div></article>)}</section>;
}
