"use client";

import { useEffect, useMemo, useRef, useState } from "react";

const OWNER={K:"Kalena",P:"Paris",Both:"Kalena + Paris"};
const AREAS=["Brand","Audience","Content","Roadmap","Opportunities","Performance","Reference"];
const PROOF_LABELS=["Scenario","Lab demonstration","Sourced report","Design partner result","Customer case","No claim"];
const TERMINAL=new Set(["Archived","Done","Published"]);
const sourceHref=source=>`/api/sources/${source.id}/file`;

export function WorkspaceModal({title,kicker,children,close,wide=false,actions=null}){
  useEffect(()=>{const key=event=>event.key==="Escape"&&close();window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[close]);
  return <div className="workspace-layer" onMouseDown={event=>event.target===event.currentTarget&&close()}>
    <section className={`workspace-modal${wide?" wide":""}`}>
      <header><div><small>{kicker}</small><h1>{title}</h1></div><div className="workspace-head-actions">{actions}<button className="round-close" onClick={close} aria-label="Close">×</button></div></header>
      <div className="workspace-scroll">{children}</div>
    </section>
  </div>;
}

export function MemoryPanel({sources,entries,mismatches,connectors,onUpload,onRefresh,onUpdate,onArchiveSource,onCreateMemory,onUpdateMemory,status}){
  const filesRef=useRef(null),folderRef=useRef(null);
  const [tab,setTab]=useState("intelligence"),[area,setArea]=useState("All"),[editing,setEditing]=useState(null);
  const [draft,setDraft]=useState({summary:"",document_type:"",destination:""});
  const [newMemory,setNewMemory]=useState({area:"Brand",title:"",body:""});
  async function chosen(list){for(const file of Array.from(list||[]))await onUpload(file);await onRefresh();}
  const visible=entries.filter(item=>area==="All"||item.area===area);
  return <div className="memory-workspace">
    <section className="memory-intro"><div><span>What Bleuprint knows — and why</span><h2>{entries.length} sourced entr{entries.length===1?"y":"ies"}</h2><p>Every entry is labelled as extracted, confirmed, suggested, or conflicted and keeps its exact source location. Uploading a file never silently turns a guess into brand truth.</p></div><div className="memory-upload-actions"><button onClick={()=>folderRef.current?.click()}>Import Passport folder</button><button onClick={()=>filesRef.current?.click()}>Add files</button><input ref={filesRef} hidden multiple type="file" onChange={event=>chosen(event.target.files)}/><input ref={folderRef} hidden multiple type="file" webkitdirectory="" onChange={event=>chosen(event.target.files)}/></div></section>
    <p className="workspace-status">{status}</p>
    <nav className="memory-tabs"><button className={tab==="intelligence"?"active":""} onClick={()=>setTab("intelligence")}>Intelligence</button><button className={tab==="sources"?"active":""} onClick={()=>setTab("sources")}>Source files · {sources.length}</button><button className={tab==="connectors"?"active":""} onClick={()=>setTab("connectors")}>Connections</button></nav>
    {mismatches.length?<section className="memory-signals"><span>{mismatches.length} NEED JUDGMENT</span>{mismatches.slice(0,4).map(item=><p key={item.id}><b>{item.document_name||"Workspace"}</b> · {item.detail} <em>{item.source_location}</em></p>)}</section>:null}
    {tab==="intelligence"?<>
      <section className="memory-capture"><select value={newMemory.area} onChange={event=>setNewMemory(current=>({...current,area:event.target.value}))}>{AREAS.map(item=><option key={item}>{item}</option>)}</select><input value={newMemory.title} onChange={event=>setNewMemory(current=>({...current,title:event.target.value}))} placeholder="Decision or fact title"/><textarea value={newMemory.body} onChange={event=>setNewMemory(current=>({...current,body:event.target.value}))} placeholder="Write the exact decision. Use @Paris or @Kalena to notify a teammate."/><button onClick={async()=>{if(await onCreateMemory(newMemory))setNewMemory(current=>({...current,title:"",body:""}));}}>Add confirmed memory</button></section>
      <nav className="area-tabs">{["All",...AREAS].map(item=><button key={item} className={area===item?"active":""} onClick={()=>setArea(item)}>{item}<small>{item==="All"?entries.length:entries.filter(entry=>entry.area===item).length}</small></button>)}</nav>
      <section className="memory-entry-list">{visible.length?visible.map(item=><MemoryEntry key={item.id} item={item} onUpdate={onUpdateMemory}/>):<div className="empty-workspace"><h3>No intelligence in this area yet.</h3><p>Add an explicit decision above or upload the source document that contains it.</p></div>}</section>
    </>:null}
    {tab==="sources"?<section className="memory-records">{sources.length?sources.map(source=><article key={source.id} className={source.is_record?"is-record":""}><div className="memory-meta"><span>{source.document_type}</span><small>{source.destination}</small></div><h3><a href={sourceHref(source)} target="_blank" rel="noreferrer">{source.name}</a></h3>{editing===source.id?<div className="memory-edit"><textarea value={draft.summary} onChange={event=>setDraft(current=>({...current,summary:event.target.value}))}/><input aria-label="Document type" value={draft.document_type} onChange={event=>setDraft(current=>({...current,document_type:event.target.value}))}/><input aria-label="Destination" value={draft.destination} onChange={event=>setDraft(current=>({...current,destination:event.target.value}))}/><button onClick={async()=>{await onUpdate(source.id,draft);setEditing(null);}}>Save source note</button><button onClick={()=>setEditing(null)}>Cancel</button></div>:<p>{source.context?.summary?.slice(0,420)||"Stored. Text extraction is not available for this format yet."}</p>}<footer><a href={sourceHref(source)} target="_blank" rel="noreferrer">Open source ↗</a><button onClick={()=>{setEditing(source.id);setDraft({summary:source.context?.summary||"",document_type:source.document_type||"reference",destination:source.destination||"Source inbox"});}}>Edit note</button><button className={source.is_record?"confirmed":""} onClick={()=>onUpdate(source.id,{markRecord:true})}>{source.is_record?"Confirmed record":"Confirm as record"}</button><button className="danger-text" onClick={()=>onArchiveSource(source.id)}>Archive</button></footer></article>):<div className="empty-workspace"><h3>Clean workspace ready.</h3><p>Start with the canonical context, brand guide, mission plan, roadmap, launch-week plan, and current captions/assets. Old portal demo sources are not treated as truth.</p></div>}</section>:null}
    {tab==="connectors"?<section className="connector-list">{connectors.map(item=><article key={item.id}><i className={item.state==="ready"?"ready":""}/><div><h3>{item.name}</h3><p>{item.mode}</p></div><strong>{item.state.replaceAll("-"," ")}</strong></article>)}</section>:null}
  </div>;
}

function MemoryEntry({item,onUpdate}){
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState({area:item.area,title:item.title,body:item.body,status:item.status});
  return <article className={`memory-entry ${item.status}`}><header><span>{item.area}</span><b>{item.status.replaceAll("_"," ")}</b></header>{editing?<><input value={draft.title} onChange={event=>setDraft(current=>({...current,title:event.target.value}))}/><textarea value={draft.body} onChange={event=>setDraft(current=>({...current,body:event.target.value}))}/><div className="memory-entry-actions"><select value={draft.area} onChange={event=>setDraft(current=>({...current,area:event.target.value}))}>{AREAS.map(area=><option key={area}>{area}</option>)}</select><select value={draft.status} onChange={event=>setDraft(current=>({...current,status:event.target.value}))}>{["extracted","confirmed","suggested","conflict","needs_decision"].map(status=><option key={status}>{status}</option>)}</select><button onClick={async()=>{await onUpdate(item.id,draft);setEditing(false);}}>Save</button><button onClick={()=>setEditing(false)}>Cancel</button></div></>:<><h3>{item.title}</h3><p>{item.body}</p><footer><div><strong>{item.source_name||"Team entry"}</strong><span>{item.source_location||"Direct entry"}</span></div><small>Updated by {item.updated_by}</small><button onClick={()=>setEditing(true)}>Edit</button><button onClick={()=>onUpdate(item.id,{action:"archive"})}>Archive</button></footer></>}</article>;
}

export function RoadmapPanel({roadmap,onSave,onUpload,onOpenContent,member}){
  const [filter,setFilter]=useState("open");
  const state=roadmap?.state||{done:{},blocked:{},questions:{},attachments:{},archived:{}};
  const phases=roadmap?.phases||[];const all=phases.flatMap(phase=>phase.tasks.map(task=>({...task,phase:phase.name})));
  const doneCount=all.filter(task=>state.done?.[task.id]).length;
  function update(next){onSave({done:state.done||{},blocked:state.blocked||{},questions:state.questions||{},attachments:state.attachments||{},archived:state.archived||{},...next});}
  function toggle(task){update({done:{...(state.done||{}),[task.id]:!state.done?.[task.id]}});}
  function question(task,value){if(value!==(state.questions?.[task.id]||""))update({questions:{...(state.questions||{}),[task.id]:value}});}
  function blocked(task){const next={...(state.blocked||{})};if(next[task.id])delete next[task.id];else next[task.id]={by:member.name,at:new Date().toISOString()};update({blocked:next});}
  function archiveTask(task){update({archived:{...(state.archived||{}),[task.id]:{by:member.name,at:new Date().toISOString()}}});}
  function restoreTask(task){const next={...(state.archived||{})};delete next[task.id];update({archived:next});}
  async function attach(task,file){if(!file)return;const doc=await onUpload(file);if(!doc)return;update({attachments:{...(state.attachments||{}),[task.id]:[...(state.attachments?.[task.id]||[]),{id:doc.id,name:doc.name}]}});}
  return <div className="roadmap-workspace"><section className="roadmap-summary"><div><span>SHARED ROADMAP</span><strong>{doneCount}</strong><small>of {all.length} complete</small></div><p>The roadmap is the operating order. Add @Paris or @Kalena to a question to create a live team update. Completed work can move into Archive without being deleted.</p><nav>{["open","bottlenecks","done","archive","all"].map(item=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</nav></section>{phases.map(phase=>{const visible=phase.tasks.filter(task=>filter==="all"||(filter==="archive"&&state.archived?.[task.id])||(filter==="done"&&state.done?.[task.id]&&!state.archived?.[task.id])||(filter==="bottlenecks"&&state.blocked?.[task.id]&&!state.archived?.[task.id])||(filter==="open"&&!state.done?.[task.id]&&!state.archived?.[task.id]));return visible.length?<section className="roadmap-phase" key={phase.id}><header><span>{phase.number}</span><div><h2>{phase.name}</h2><p>{phase.why}</p></div><small>{phase.when}</small></header>{visible.map(task=><article key={task.id} className={`${state.done?.[task.id]?"done ":""}${state.blocked?.[task.id]?"blocked":""}`}><button className="roadmap-check" onClick={()=>toggle(task)}>{state.done?.[task.id]?"✓":""}</button><div><h3>{task.title}{task.key?<b>KEY</b>:null}</h3><p>{task.detail}</p>{state.attachments?.[task.id]?.length?<div className="roadmap-attachments">{state.attachments[task.id].map(file=><a key={file.id} href={`/api/sources/${file.id}/file`} target="_blank" rel="noreferrer">{file.name} ↗</a>)}</div>:null}<textarea defaultValue={state.questions?.[task.id]||""} onBlur={event=>question(task,event.target.value)} placeholder="Question, missing document, decision, or @team mention…"/></div><aside><span>{OWNER[task.owner]||task.owner}</span><small>{task.due}</small>{state.archived?.[task.id]?<button onClick={()=>restoreTask(task)}>Restore</button>:<><button onClick={()=>blocked(task)}>{state.blocked?.[task.id]?"Clear bottleneck":"Flag bottleneck"}</button><label className="roadmap-attach">Attach file<input hidden type="file" onChange={event=>attach(task,event.target.files?.[0])}/></label>{state.done?.[task.id]?<button onClick={()=>archiveTask(task)}>Archive</button>:null}{/content|post|social|campaign/i.test(task.title)?<button onClick={onOpenContent}>Open content</button>:null}</>}</aside></article>)}</section>:null;})}</div>;
}

function dueValue(row){const value=Date.parse(`${row.date||row.day||""} ${row.time||""}`);return Number.isFinite(value)?value:Number.MAX_SAFE_INTEGER;}
export function ContentPanel({calendar,campaigns,onSave,onUpload,onAnalyze,analysis,status,onOpenIssues,buffer,onBufferSync}){
  const [channel,setChannel]=useState("Instagram"),[activeId,setActiveId]=useState(null);
  const rows=useMemo(()=>calendar.filter(row=>row.channel===channel&&row.status!=="Archived").sort((a,b)=>dueValue(a)-dueValue(b)),[calendar,channel]);
  const active=calendar.find(row=>row.id===activeId&&row.status!=="Archived");
  const next=rows.find(row=>!TERMINAL.has(row.status)&&dueValue(row)>=Date.now()-86400000)||rows.find(row=>!TERMINAL.has(row.status))||null;
  function updateRow(id,changes){return onSave(calendar.map(row=>row.id===id?{...row,...changes}:row),campaigns);}
  function archiveRow(row){updateRow(row.id,{status:"Archived",previousStatus:row.status,archivedAt:new Date().toISOString()});}
  function addRow(){const row={id:`content-${Date.now()}`,date:new Date().toISOString().slice(0,10),day:new Date().toISOString().slice(0,10),channel,format:channel==="LinkedIn"?"text":"reel",title:"New planned post",time:channel==="LinkedIn"?"08:30 ET":"12:00 ET",status:"Draft",sourceDocument:"Team content calendar",campaignKey:`campaign-${Date.now()}`};onSave([...calendar,row],campaigns);setActiveId(row.id);}
  if(active)return <CampaignPanel row={active} calendar={calendar} campaigns={campaigns} back={()=>setActiveId(null)} save={(nextCampaign,nextRows=calendar)=>onSave(nextRows,[nextCampaign,...campaigns.filter(item=>item.id!==nextCampaign.id)])} upload={onUpload} analyze={onAnalyze} analysis={analysis} onOpenIssues={onOpenIssues}/>;
  return <div className="content-workspace"><section className="content-overview"><div><span>CONTENT / LIVE CALENDAR</span><h2>Calendar first. Campaign follows.</h2><p>The next post is selected by its real scheduled date and status. Every edit saves to the shared workspace, and a campaign opens from that exact row.</p></div><div className="content-actions"><button onClick={()=>next&&setActiveId(next.id)} disabled={!next}>Open next {channel} post</button><button onClick={addRow}>Add {channel} post</button></div></section><nav className="platform-tabs">{["Instagram","TikTok","LinkedIn"].map(item=><button key={item} onClick={()=>setChannel(item)} className={channel===item?"active":""}>{item}<small>{calendar.filter(row=>row.channel===item&&row.status!=="Archived").length}</small></button>)}</nav><section className="content-list">{rows.length?rows.map(row=><article key={row.id}><div className="content-row-edit"><input type="date" value={/^\d{4}-\d{2}-\d{2}$/.test(row.date||"")?row.date:""} onChange={event=>updateRow(row.id,{date:event.target.value,day:event.target.value})}/><input value={row.title||""} onChange={event=>updateRow(row.id,{title:event.target.value})}/><select value={row.format||"unspecified"} onChange={event=>updateRow(row.id,{format:event.target.value})}>{["reel","carousel","video","single image","text","carousel PDF","unspecified"].map(item=><option key={item}>{item}</option>)}</select><input value={row.time||""} onChange={event=>updateRow(row.id,{time:event.target.value})}/><small>{row.sourceDocument||"Team content calendar"}</small></div><div className="content-row-actions"><select value={row.status||"Draft"} onChange={event=>updateRow(row.id,{status:event.target.value})}>{["Draft","In approval","Approved","Scheduled","Published","Done","Blocked"].map(item=><option key={item}>{item}</option>)}</select><button onClick={()=>setActiveId(row.id)}>Build campaign</button><button onClick={()=>archiveRow(row)}>Archive</button></div></article>):<div className="empty-workspace"><h3>No {channel} posts yet.</h3><p>Add one here or upload a calendar source. Bleuprint will not invent a schedule.</p></div>}</section><footer className="content-foot"><span>{status}</span><div><button onClick={onBufferSync}>{buffer?.state==="ready"?"Sync Buffer":"Connect Buffer to sync"}</button><button onClick={()=>onAnalyze(calendar,campaigns)}>Analyze the whole week</button></div></footer>{analysis?<AlignmentResults analysis={analysis} onOpenIssues={onOpenIssues}/>:null}</div>;
}

function blankOutput(row){return{format:row.format||"post",proof:row.proof||"",caption:row.captionA||row.copy?.a||row.copy||"",alternate:row.captionB||row.copy?.b||"",script:row.script||row.screen||"",brief:row.brief||"",assets:[],slides:Array.from({length:/carousel/i.test(row.format||"")?5:0},()=>({copy:"",asset:null}))};}
function CampaignPanel({row,calendar,campaigns,back,save,upload,analyze,analysis,onOpenIssues}){
  const campaignKey=row.campaignKey||row.campaignId||row.id;const related=calendar.filter(item=>item.id===row.id||(item.campaignKey||item.campaignId)===campaignKey);const campaignId=`campaign-${campaignKey}`;
  const existing=campaigns.find(item=>item.id===campaignId||item.id===`post-${row.id}`);const initial=existing||{id:campaignId,calendarId:row.id,calendarIds:related.map(item=>item.id),campaignKey,title:row.title,week:row.week||"Current week",status:row.status||"Draft",outputs:Object.fromEntries(related.map(item=>[item.channel,{...blankOutput(item),calendarId:item.id}]))};
  const [campaign,setCampaign]=useState(initial),[platform,setPlatform]=useState(row.channel),[saving,setSaving]=useState("");const output=campaign.outputs[platform]||blankOutput(row);
  function change(changes){setCampaign(current=>({...current,outputs:{...current.outputs,[platform]:{...(current.outputs[platform]||blankOutput(row)),...changes}}}));}
  async function attach(file,slideIndex=null){if(!file)return;setSaving(`Storing ${file.name}…`);const doc=await upload(file);if(!doc){setSaving("Upload failed");return;}const asset={id:doc.id,name:doc.name,type:doc.content_type};if(slideIndex===null)change({assets:[...(output.assets||[]),asset]});else{const slides=[...(output.slides||[])];slides[slideIndex]={...slides[slideIndex],asset};change({slides});}setSaving(`${file.name} shared with the team`);}
  async function store(status=campaign.status){const next={...campaign,status,updatedAt:new Date().toISOString()};setCampaign(next);const ids=new Set(related.map(item=>item.id));const nextRows=calendar.map(item=>ids.has(item.id)?{...item,status,campaignId:next.id,campaignKey}:item);const ok=await save(next,nextRows);setSaving(ok===false?"Save failed":"Saved to the shared Passport workspace");}
  return <div className="campaign-production"><button className="back-button" onClick={back}>← Back to calendar</button><header><div><span>{campaign.week} / CAMPAIGN</span><h2>{campaign.title}</h2><p>{row.date||row.day} · generated from this calendar post and its connected sources.</p></div><div><button onClick={()=>store("Draft")}>Save</button><button className="approve" onClick={()=>store("Approved")}>Approve + update calendar</button></div></header><nav className="platform-tabs">{Object.keys(campaign.outputs).map(item=><button className={platform===item?"active":""} key={item} onClick={()=>setPlatform(item)}>{item}</button>)}</nav><section className="production-grid"><article><span>Direction</span><label>Brief<textarea value={output.brief||""} onChange={event=>change({brief:event.target.value})}/></label><label>Proof label<select value={output.proof||""} onChange={event=>change({proof:event.target.value})}><option value="">Select evidence level</option>{PROOF_LABELS.map(item=><option key={item}>{item}</option>)}</select></label><label>Script / on-screen direction<textarea value={output.script||""} onChange={event=>change({script:event.target.value})}/></label></article><article><span>Copy</span><label>Primary copy<textarea className="tall" value={output.caption||""} onChange={event=>change({caption:event.target.value})}/></label><label>Alternate<textarea value={output.alternate||""} onChange={event=>change({alternate:event.target.value})}/></label></article><article><span>{/carousel/i.test(output.format)?"Carousel build":"Media"}</span>{/carousel/i.test(output.format)?<div className="slide-stack">{output.slides.map((slide,index)=><div key={index}><label className="asset-drop">{slide.asset?.name||`Add image ${index+1}`}<input type="file" accept="image/*" onChange={event=>attach(event.target.files?.[0],index)}/></label><textarea value={slide.copy||""} onChange={event=>{const slides=[...output.slides];slides[index]={...slide,copy:event.target.value};change({slides});}} placeholder={`Slide ${index+1} copy`}/></div>)}</div>:<><label className="asset-drop large">Add or replace {platform==="LinkedIn"?"supporting asset":"video / cover"}<input type="file" accept="image/*,video/*" onChange={event=>attach(event.target.files?.[0])}/></label>{output.assets?.map(asset=><p className="asset-name" key={asset.id}>{asset.name}</p>)}</>}</article></section><footer><span>{saving}</span><button onClick={()=>analyze(calendar,[campaign,...campaigns.filter(item=>item.id!==campaign.id)])}>Check alignment</button></footer>{analysis?<AlignmentResults analysis={analysis} onOpenIssues={onOpenIssues}/>:null}</div>;
}

export function AlignmentResults({analysis,onOpenIssues}){const findings=analysis?.checks||analysis?.findings||[];return <section className="alignment-results"><header><span>ALIGNMENT CHECK</span><h3>{analysis?.title||"What needs attention"}</h3>{findings.length&&onOpenIssues?<button onClick={onOpenIssues}>Resolve in Signals</button>:null}</header>{findings.map((finding,index)=>typeof finding==="string"?<article key={index}><b>Review</b><p>{finding}</p></article>:<article key={finding.id||index} className={finding.severity||"review"}><b>{finding.severity||"review"}</b><div><h4>{finding.title||finding.message}</h4>{finding.message&&finding.title?<p>{finding.message}</p>:null}<small>{finding.affectedOutput||"Workspace"} · {finding.evidenceDocument||finding.evidence?.document||"Passport memory"}{finding.evidenceLocation||finding.evidence?.location?` · ${finding.evidenceLocation||finding.evidence.location}`:""}</small><em>{finding.recommendation}</em></div></article>)}</section>;}

export function IssuesPanel({issues,notifications,onUpdate,onReadNotifications,member}){
  const active=issues.filter(item=>["open","assigned"].includes(item.status));const closed=issues.filter(item=>["resolved","dismissed"].includes(item.status));
  return <div className="issues-workspace"><section className="notification-strip"><div><span>LIVE TEAM UPDATES</span><h2>{notifications.filter(item=>!item.read_at).length} unread</h2><p>Mentions update here within ten seconds. Email is queued once Microsoft is authorized.</p></div><button onClick={onReadNotifications}>Mark read</button></section>{notifications.slice(0,5).map(item=><article className={`team-notification${item.read_at?" read":""}`} key={item.id}><b>{item.title}</b><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString()} · email {item.email_state.replaceAll("_"," ")}</small></article>)}<header className="issue-heading"><span>OPEN SIGNALS</span><h2>{active.length} need attention</h2><p>Resolving records who did it and when. A reason is requested but optional. Strategy impact is added to memory only when you explicitly apply it.</p></header><section className="issue-list">{active.length?active.map(issue=><IssueCard key={issue.id} issue={issue} onUpdate={onUpdate} member={member}/>):<div className="empty-workspace"><h3>No open issues.</h3><p>Run Analyze in Content or upload a changed source to create evidence-backed signals.</p></div>}</section>{closed.length?<details className="closed-issues"><summary>{closed.length} recently resolved or dismissed</summary>{closed.slice(0,12).map(item=><p key={item.id}><b>{item.status}</b> · {item.detail} · {item.resolved_by}</p>)}</details>:null}</div>;
}
function IssueCard({issue,onUpdate,member}){
  const impactData=issue.impact||{};const [note,setNote]=useState("");const [assignedTo,setAssignedTo]=useState(issue.assigned_to||"");const [area,setArea]=useState(AREAS.includes(impactData.area)?impactData.area:"Brand");const [impact,setImpact]=useState(impactData.summary||"");const [apply,setApply]=useState(false);
  const submit=status=>onUpdate(issue.id,{status,resolutionNote:note,assignedTo:assignedTo||null,impact:{...impactData,area,summary:impact,title:impactData.title||`Issue resolution by ${member.name}`},applyImpact:status==="resolved"&&apply&&Boolean(impact.trim())});
  return <article><header><div><b>{impactData.severity||issue.mismatch_type.replace("alignment_","").replaceAll("_"," ")}</b><h3>{impactData.title||issue.detail}</h3></div><span>{issue.status}</span></header>{impactData.title?<p>{issue.detail}</p>:null}<small>{issue.document_name||"Workspace"} · {issue.source_location||"Team review"}</small>{impactData.recommendation?<em>{impactData.recommendation}</em>:null}<div className="issue-controls"><label>Assign<select value={assignedTo} onChange={event=>setAssignedTo(event.target.value)}><option value="">Unassigned</option><option value="@Kalena">Kalena</option><option value="@Paris">Paris</option></select></label><label>Why / resolution note <span>optional</span><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="What changed or why this is being bypassed…"/></label><label>Effect on strategy<select value={area} onChange={event=>setArea(event.target.value)}>{AREAS.filter(item=>item!=="Reference").map(item=><option key={item}>{item}</option>)}</select><textarea value={impact} onChange={event=>setImpact(event.target.value)} placeholder="Describe the direct effect; leave blank if there is none."/></label><label className="apply-impact"><input type="checkbox" checked={apply} onChange={event=>setApply(event.target.checked)}/> Apply this exact impact to {area} memory</label></div><footer><button onClick={()=>submit(assignedTo?"assigned":"open")}>Save assignment</button><button onClick={()=>submit("resolved")}>Resolve</button><button onClick={()=>submit("dismissed")}>Bypass + record</button><button onClick={()=>submit("archived")}>Archive</button></footer></article>;
}

export function PerformancePanel({performance,calendar,connectors,onSyncBuffer,status}){
  const buffer=connectors.find(item=>item.id==="buffer")||performance.buffer||{};const totals={};for(const item of performance.metrics||[])totals[item.metric]=(totals[item.metric]||0)+Number(item.value||0);
  const planned=calendar.filter(row=>!["Archived","Done"].includes(row.status)).sort((a,b)=>dueValue(a)-dueValue(b)).slice(0,10);
  return <div className="performance-workspace"><section className="performance-hero"><div><span>FEEDBACK LOOP</span><h2>Know what shipped. Learn what changed.</h2><p>Calendar records match Buffer posts, scheduled and sent status comes back automatically, and post-level metrics become evidence for the next campaign.</p></div><button onClick={onSyncBuffer}>{buffer.state==="ready"?"Sync Buffer now":"Buffer needs its API key"}</button></section><p className="workspace-status">{status}</p><section className="performance-metrics">{Object.keys(totals).length?Object.entries(totals).map(([name,value])=><article key={name}><span>{name}</span><strong>{value.toLocaleString()}</strong><small>Buffer · provisional</small></article>):<div className="empty-workspace"><h3>No performance data yet.</h3><p>Once the Buffer key is connected, Bleuprint can match scheduled and sent posts and import available post metrics. Buffer reports can be up to about 24 hours behind the social network.</p></div>}</section><section className="performance-plan"><header><span>NEXT POSTS</span><h2>Publishing watch</h2></header>{planned.length?planned.map(row=><article key={row.id}><time>{row.date||row.day}</time><div><strong>{row.title}</strong><small>{row.channel} · {row.format} · {row.time}</small></div><b>{row.bufferStatus||row.status}</b></article>):<p>No active calendar rows. Add the next planned post in Content.</p>}</section>{performance.missing?.length?<section className="memory-signals"><span>THREE-DAY WARNING</span>{performance.missing.map((item,index)=><p key={index}>{item.channel||"Content"} has nothing ready for {item.date||"the upcoming slot"}.</p>)}</section>:null}</div>;
}

export function ArchivePanel({archive,onRestore}){
  const [tab,setTab]=useState("work");const work=archive.content||[];const stored=[...(archive.documents||[]).map(item=>({...item,type:"document",label:item.name,meta:`${item.document_type} · ${item.destination}`})),...(archive.memory||[]).map(item=>({...item,type:"memory",label:item.title,meta:`${item.area} · ${item.source_name||"Team entry"}`})),...(archive.issues||[]).map(item=>({...item,type:"issue",label:item.detail,meta:`${item.status} · ${item.source_location||"Team review"}`})),...(archive.archivedContent||[]).map(item=>({...item,type:"content",label:item.title,meta:`${item.channel||"Content"} · ${item.date||item.day||"No date"} · was ${item.previousStatus||"Draft"}`}))];
  return <div className="archive-workspace"><nav className="memory-tabs"><button className={tab==="work"?"active":""} onClick={()=>setTab("work")}>Approved + done · {work.length}</button><button className={tab==="stored"?"active":""} onClick={()=>setTab("stored")}>Archived records · {stored.length}</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>Change history · {archive.events?.length||0}</button></nav>{tab==="work"?<section className="archive-list">{work.length?work.map(item=><article key={item.id}><i/><div><small>{item.type}</small><h2>{item.title}</h2><p><strong>{item.document}</strong><span>{item.location}</span></p></div><aside><b>{item.status}</b><span>{item.approvedBy}</span>{item.at?<time>{new Date(item.at).toLocaleString()}</time>:null}</aside></article>):<div className="empty-workspace"><h3>No approved or completed work yet.</h3></div>}</section>:null}{tab==="stored"?<section className="archive-records">{stored.length?stored.map(item=><article key={`${item.type}-${item.id}`}><div><span>{item.type}</span><h3>{item.label}</h3><p>{item.meta}</p></div><button onClick={()=>onRestore(item.type,item.id)}>Restore</button></article>):<div className="empty-workspace"><h3>Nothing is archived.</h3></div>}</section>:null}{tab==="history"?<section className="history-list">{(archive.events||[]).map(item=><article key={item.id}><time>{new Date(item.created_at).toLocaleString()}</time><div><strong>{item.event_type.replaceAll("."," · ")}</strong><p>{item.source_name||"Workspace"}{item.source_location?` · ${item.source_location}`:""}</p></div><span>{item.actor_email}</span></article>)}</section>:null}</div>;
}
